### PR TITLE
[feat] Multiplayer network, ball jump control, respawn teleport, and respondence to user input, Close #4 #7 #63

### PR DESCRIPTION
**Pull request by lemonchu**
Close #4 #7 #63 
### New Feature: Cross-Platform Compatible Multiplayer Network (UDP) for Linux, Windows, and Mac

**Implemented Features:**
1. **Mode Selection**: we have `room`, `client`, and `local` mode. 

`room` mode is for the host of a playground. 

`client` mode is for connecting to the room to join the party. 

`local` mode is for playing with the dead ball for practice.

2. **Compressed Data Transfer**: Credit to Yuchen Yang for designing a wonderful compression scheme for transferring user inputs.

**Usage:**

- `GameBall --mode=local`
- `GameBall --mode=client --address=192.168.1.1 (your ip) --port=1115 (default port is 1115)`
- `GameBall --mode=room --port=1115 (your server port, default is 1115)`

`Room` mode will automatically show room ip in the console

### Enhancements: Ball Jumping Mechanism

**Implemented Features:**
1. **Jump Activation via Left Mouse Click**: The ball is now programmed to jump when the left mouse button is clicked. 

2. **Grounded Jump Constraint**: To add realism and challenge, the ball can only jump when it is in contact with the ground. This restriction prevents continuous mid-air jumps.

3. **Single Jump per Click**: The ball will perform a single jump for each click of the left mouse button. Holding the button down won't cause multiple jumps.

4. **Consistent Spin During Airborne State**: While the ball is airborne post-jump, its spinning motion remains constant. This detail ensures a seamless visual experience.
### Enhancements: Ball Respawn Mechanism

This mechanism is simply teleporting the fallen ball back to the playground. 

### Known issue:

1. **Client Quit Corrupts the Game**: Due to the imperfection of the logic of GameX, this multiplayer network can not handle clients quitting properly now. Even though I tried to write some lines of this Quit logic, it won't stop occurring segmentation fault and null pointer dereference. 

The main cause of segmentation fault and null pointer dereference is the Actor Cleaning Mechanism in GameBall::OnUpdate(), hope it can be fixed in the future.

2. **Port Customization Logic**: Currently, the client not only needs to input the host's port but is also required to define its own port. However, the game settings only provide a single 'port' variable, leading to configuration challenges.

Due to time constraints and exhaustion, I implemented a temporary solution where the client's port is automatically set to the host port number + 1. Hoping we can revisit this issue in the future to develop a more robust and user-friendly solution for port configuration in our game.

3. **Latency to be Improved**: The sync relies on smooth connection heavily. High latency occurred in client side. 

However, if client and host share the same ip(same device), the latency nearly disappeared. 

Looking forward to feedback and suggestions!

### CODE REVIEW

**Comment by lemonchu** [comment]
Close #4

**Comment by lemonchu** [comment]
Close #4 #7 #63

**Comment by lemonchu** [comment]
Test Videos

2 Player Test (With Yuchen Yang)
https://github.com/Yao-class-cpp-studio/GameX/assets/44695478/d0cd9cf9-f69e-4676-bbc2-a0758ac22ca6

3 Player Test (Yuchen Yang 1 ball, LemonPig 2 balls)
https://github.com/Yao-class-cpp-studio/GameX/assets/44695478/c8ee8a3a-45c2-42b2-a242-90680b555659

**Comment by chenzunh23** [comment]
Fancy game! You have been working on this strenuously since the calculus exam, right?

**Comment by lemonchu** [comment]
> Fancy game! You have been working on this strenuously since the calculus exam, right?

Thanks for your praise! Unfortunately, after examining my commits I found that my code is a total piece of rubbish. Maybe I will close this pull request and rewrite the network feature. 

I have written the communication at the wrong place.

**Comment by lemonchu** [comment]
This PR is closed because it is really a piece of shit code. A new PR is on the way!

**Pull request closed without merging**
